### ISSUE TITLE
Completion doesnt work

### ISSUE THREAD

**Issue by matthiasg** [Microsoft/TypeScript-Sublime-Plugin#143]
Completion etc does not work at all:

Console output when opening a *.ts file:

```reloading Packages/typescript/Preferences.sublime-settings
reloading plugin typescript.TypeScript
2015-04-14 14:51:05,560: WARNING: TypeScript plugin initialized.
initialize typescript...
3083
spawning node module: C:\Users\Matthias\AppData\Roaming\Sublime Text 3\Packages\typescript\tsserver\tsserver.js
Found node executable at node
request: {"seq": 1, "type": "request", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "tabSize": 4}}, "command": "configure"}
queue timeout
request: {"seq": 2, "type": "request", "arguments": {"file": "c:\\Development\\Test\\AngularTypescriptEs6\\src\\app\\app.module.ts"}, "command": "open"}
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 127, in reload_plugin
    el.on_activated(v)
  File "C:\Users\Matthias\AppData\Roaming\Sublime Text 3\Packages\typescript\TypeScript.py", line 523, in on_activated
    info = self.getInfo(view)
  File "C:\Users\Matthias\AppData\Roaming\Sublime Text 3\Packages\typescript\TypeScript.py", line 500, in getInfo
    open_file(view)
  File "C:\Users\Matthias\AppData\Roaming\Sublime Text 3\Packages\typescript\TypeScript.py", line 417, in open_file
    cli.service.open(view.file_name())
  File "C:\Users\Matthias\AppData\Roaming\Sublime Text 3\Packages\typescript\libs\serviceproxy.py", line 88, in open
    self.__comm.postCmd(jsonStr)
  File "C:\Users\Matthias\AppData\Roaming\Sublime Text 3\Packages\typescript\libs\nodeclient.py", line 163, in postCmd
    self.__serverProc.stdin.flush()
OSError: [Errno 22] Invalid argument
reloading Packages/typescript/TypeScript.sublime-settings```


This is on Windows x64. Sublime 3. Build 3083. No previous typescript enabled. 

Anybody an idea what the issue might be ?

**Comment by steveluc** [comment]
The server is not up (invalid argument to stdin.flush() shows this as well as queue timeout messages).  Most likely cause is node was not found.  If your node is installed in a place not on your system path, then you can add a 'node\_path' setting to your Preferences.sublime_settings file (see README.md for more details).

**Comment by matthiasg** [comment]
@steveluc thanks for the feedback. node was in the path (`where node` worked fine).

It turns out the issue was a leftover folder of the manual TypeScript installation of before.
I had recently reinstalled windows and also reinstalled sublime but the Sublime `Installed Packages` folder was still present, including the previous `TypeScript` package. The current one is just `typescript`.

Works now.
