### ISSUE TITLE
Async reload broken

### ISSUE THREAD

**Issue by musicist288** [Microsoft/TypeScript-Sublime-Plugin#165]
Got the following traceback from the sublime console:

````
AttributeError: 'module' object has no attribute 'ReloadRequest'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/home/vagrant/.config/sublime-text-3/Packages/TypeScript/TypeScript.py", line 1049, in run
    checkUpdateView(self.view)
  File "/home/vagrant/.config/sublime-text-3/Packages/TypeScript/TypeScript.py", line 504, in checkUpdateView
    reloadBuffer(view, clientInfo)
  File "/home/vagrant/.config/sublime-text-3/Packages/TypeScript/TypeScript.py", line 491, in reloadBuffer
    cli.service.reloadAsync(view.file_name(), tmpfileName, recv_reload_response)
  File "/home/vagrant/.config/sublime-text-3/Packages/TypeScript/libs/serviceproxy.py", line 130, in reloadAsync
    req = servicedefs.ReloadRequest(self.incrSeq(), servicedefs.ReloadRequestArgs(path, alternatePath))
````

Looks like the last two merges stepped on each other a bit?
https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/163
https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/161

**Comment by zhengbli** [comment]
Yeah you are right, the two commits broke each other. Fixed in #166
