### ISSUE TITLE
Errors get logged at every keystroke when there is an empty view group

### ISSUE THREAD

**Issue by hoanhtien** [Microsoft/TypeScript-Sublime-Plugin#245]
Repro steps:
1. Enable two-column layout. Open a ts file on the left column while leaving the other column blank.
2. Close and re-open Sublime.
3. Open the console (<code>Ctrl + `</code>)
4. Start typing something in the ts file. The following error gets logged in the console at *every keystroke*:
```
Traceback (most recent call last):
  File "C:\Users\tihoanh\AppData\Roaming\Sublime Text 3\Packages\TypeScript-Sublime-Plugin\typescript\listeners\idle.py", line 157, in handle_time_out
    self.on_idle()
  File "C:\Users\tihoanh\AppData\Roaming\Sublime Text 3\Packages\TypeScript-Sublime-Plugin\typescript\listeners\idle.py", line 188, in on_idle
    self.request_errors(view, info, 500)
  File "C:\Users\tihoanh\AppData\Roaming\Sublime Text 3\Packages\TypeScript-Sublime-Plugin\typescript\listeners\idle.py", line 55, in request_errors
    info = get_info(group_active_view)
  File "C:\Users\tihoanh\AppData\Roaming\Sublime Text 3\Packages\TypeScript-Sublime-Plugin\typescript\libs\view_helpers.py", line 43, in get_info
    if view.file_name() is not None:
AttributeError: 'NoneType' object has no attribute 'file_name'
```
Screenshot:
![image](https://cloud.githubusercontent.com/assets/1707813/8264037/3f16dc12-1696-11e5-86cb-6c383a6f5b57.png)

**Comment by zhengbli** [comment]
Fixed in #248
