### ISSUE TITLE
close_all should not terminate tsserver

### ISSUE THREAD

**Issue by hoanhtien** [Microsoft/TypeScript-Sublime-Plugin#251]
Repro steps:
1. Open some ts files.
2. File > Close All Files, or Ctrl + Shift + P then "File: Close All".
3. Errors in console:
```
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 232, in on_close
    callback.on_close(v)
  File "C:\Users\tihoanh\AppData\Roaming\Sublime Text 3\Packages\TypeScript-Sublime-Plugin\typescript\listeners\listeners.py", line 229, in on_close
    cli.service.close(file_name)
  File "C:\Users\tihoanh\AppData\Roaming\Sublime Text 3\Packages\TypeScript-Sublime-Plugin\typescript\libs\service_proxy.py", line 113, in close
    self.__comm.postCmd(json_str)
  File "C:\Users\tihoanh\AppData\Roaming\Sublime Text 3\Packages\TypeScript-Sublime-Plugin\typescript\libs\node_client.py", line 174, in postCmd
    self.__serverProc.stdin.flush()
OSError: [Errno 22] Invalid argument
```
This is because tsserver terminates before all `on_close` callbacks are done.
4. Now open a ts file, you should see the typescript plugin does not work anymore.

**Comment by jmolero** [comment]
The error highlighting still doesn't work after closing the project.

**Comment by hoanhtien** [comment]
@jmolero Can you help elaborate the problem you are having?

**Comment by jmolero** [comment]
Now when I close and reopen a project all the features like signature popup, quick reference, etc, work. None of them was working when reopening a project. The only feature that seems to stop working after closing and reopening the project is the error highlighting. I tried typing a random text and isn't marked in red. It only works if I close and reopen sublime text.
