### ISSUE TITLE
"Notify user of TypeScript version mismatch" not working as expected

### ISSUE THREAD

**Issue by hoanhtien** [Microsoft/TypeScript-Sublime-Plugin#324]
https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/296 not working as expected on Ubuntu 14.04.3. LTS:

Error:
```
2015-08-07 16:34:38,875: 140326484469632: ERROR: Cannot parse version number from ouput: ''
```

**Comment by hoanhtien** [comment]
On MacOS, subprocess does not work as expected inside Sublime:
```
>>> subprocess.check_output(['/usr/local/bin/tsc', '-v'])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command '['/usr/local/bin/tsc', '-v']' returned non-zero exit status 127
```
although it works fine in Terminal:
```
>>> subprocess.check_output(['/usr/local/bin/tsc', '-v'])
'message TS6029: Version 1.5.3\n'
```
