### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by alexgorbatchev** [Microsoft/TypeScript-Sublime-Plugin#361]
Using TypeScript 1.6 and Sublime 3083

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 403, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/listeners.py", line 204, in on_post_text_command
    info = get_info(view)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/view_helpers.py", line 58, in get_info
    open_file(view)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/view_helpers.py", line 142, in open_file
    cli.service.open(view.file_name())
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/service_proxy.py", line 123, in open
    self.__comm.postCmd(json_str)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/node_client.py", line 142, in postCmd
    self.server_proc.stdin.write(cmd.encode())
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by hoanhtien** [comment]
@alexgorbatchev Are you still seeing this error after restarting Sublime?

**Comment by alexgorbatchev** [comment]
Yes. I found a solution. This was happening because the plugin wasn't finding node (installed via `nvm`). Setting `node_path` in the settings AND `npm install -g typescript` fixed the issue. I wish this was a more descriptive error.

**Comment by cyounkins** [comment]
I'm seeing a similar error here. I've set `node_path` in my Sublime user preferences and typescript is installed globally.

This appears in console:

```
Traceback (most recent call last):
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/idle.py", line 22, in _check_timeout_count
    self.handler()
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/idle.py", line 66, in on_idle
    self.request_errors(view, info, 500)
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/idle.py", line 105, in request_errors
    cli.service.request_get_err(error_delay, files)
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/service_proxy.py", line 194, in request_get_err
    self.__comm.postCmd(json_str)
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/node_client.py", line 143, in postCmd
    self.server_proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/idle.py", line 22, in _check_timeout_count
    self.handler()
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/idle.py", line 79, in on_selection_idle
    self.request_document_highlights(view, info)
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/idle.py", line 187, in request_document_highlights
    cli.service.async_document_highlights(view.file_name(), location, self.highlight_occurrences)
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/service_proxy.py", line 259, in async_document_highlights
    self.__comm.sendCmdAsync(json_str, on_completed, req_dict["seq"])
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/node_client.py", line 111, in sendCmdAsync
    if self.postCmd(cmd):
  File "/Users/craig/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/node_client.py", line 143, in postCmd
    self.server_proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by cyounkins** [comment]
Appears to be related to my tsconfig.json:

```
{
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by Shokodemon** [comment]
if you're using neovim + Tsukuyomi you'd need to keep a copy of tsconfig.json in our main directory as well as copy it to ./src so the the TSServer won't crash. so far so good
