### ISSUE TITLE
Unable to Paste using Command+V

### ISSUE THREAD

**Issue by jasdeepsingh** [Microsoft/TypeScript-Sublime-Plugin#453]
I'm unable to paste using CMD+V. Sublime Build: `3103`. Package version: `0.1.12`

Here's a stack trace that may be or may not be related to this issue (this is what I see whenever I open a TS file): 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 270, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/listeners.py", line 257, in on_close
    cli.service.close(file_name)
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/service_proxy.py", line 138, in close
    self.__comm.postCmd(json_str)
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/node_client.py", line 142, in postCmd
    self.server_proc.stdin.write(cmd.encode())
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 327, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/listeners/listeners.py", line 25, in on_activated
    info = get_info(view)
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/view_helpers.py", line 58, in get_info
    set_file_prefs(view)
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/view_helpers.py", line 142, in open_file
    
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/service_proxy.py", line 123, in open
    self.__comm.postCmd(json_str)
  File "/Users/jasdeep/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/libs/node_client.py", line 142, in postCmd
    self.server_proc.stdin.write(cmd.encode())
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by jasdeepsingh** [comment]
I was able to resolve this issue by manually removing the keybinding from `Default (OSX).sublime-keymap`

**Comment by zhengbli** [comment]
This is duplicate with #452. The plugin was broken, so the `format-on-paste` couldn't function. Tracking it on the other thread.
