### ISSUE TITLE
Console Error 

### ISSUE THREAD

**Issue by druckreich** [Microsoft/TypeScript-Sublime-Plugin#473]
`Traceback (most recent call last):
File "C:\Sublime Text\Data\Packages\TypeScript\typescript\listeners\idle.py",  line 22, in _check_timeout_count self.handler()
File "C:\Sublime Text\Data\Packages\TypeScript\typescript\listeners\idle.py", line 79, in on_selection_idle self.request_document_highlights(view, info)
File "C:\Sublime Text\Data\Packages\TypeScript\typescript\listeners\idle.py", line 187, in request_document_highlights    cli.service.async_document_highlights(view.file_name(), location, self.highlight_occurrences)
File "C:\Sublime Text\Data\Packages\TypeScript\typescript\libs\service_proxy.py", line 259, in async_document_highlights
self.__comm.sendCmdAsync(json_str, on_completed, req_dict["seq"])
File "C:\Sublime Text\Data\Packages\TypeScript\typescript\libs\node_client.py", line 111, in sendCmdAsync
if self.postCmd(cmd):
File "C:\Sublime Text\Data\Packages\TypeScript\typescript\libs\node_client.py", line 143, in postCmd
self.server_proc.stdin.flush()
OSError: [Errno 22] Invalid argument`

**Comment by druckreich** [comment]
Seems like my tsconfig.json is somehow now working correctly 

    {
        "compilerOptions": {
            "target": "es5",
            "module": "commonjs",
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
            "sourceMap": true
         },
         "exclude": [
              "node_modules",
              "typings/main.d.ts",
              "typings/main"
         ],
         "filesGlob": [
             "./src/**/*.ts",
             "typings/browser.d.ts",
             "src/custom-typings.d.ts"
         ]
     }

Without this the autocomplete does work. 

The Error List on the other hand now throws the following error

    Traceback (most recent call last):
      File "C:\Sublime Text Build 3103 x64\sublime_plugin.py", line 553, in run_
    return self.run()
      File "C:\Sublime Text Build 3103    x64\Data\Packages\TypeScript\typescript\commands\error_list.py", line 30, in run
    get_info(opened_view)
      File "C:\Sublime Text Build 3103 x64\Data\Packages\TypeScript\typescript\libs\view_helpers.py", line 77, in get_info
    open_file_on_worker(view)
      File "C:\Sublime Text Build 3103 x64\Data\Packages\TypeScript\typescript\libs\view_helpers.py", line 149, in open_file_on_worker
    cli.service.open_on_worker(view.file_name())
      File "C:\Sublime Text Build 3103 x64\Data\Packages\TypeScript\typescript\libs\service_proxy.py", line 132, in open_on_worker
    self.__worker_comm.postCmd(json_str)
      File "C:\Sublime Text Build 3103 x64\Data\Packages\TypeScript\typescript\libs\node_client.py", line 143, in postCmd
    self.server_proc.stdin.flush()
    OSError: [Errno 22] Invalid argument
