### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by churchilllake** [Microsoft/TypeScript-Sublime-Plugin#507]
Getting this traceback:
`
Traceback (most recent call last):

  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "TSCompletion in /Users/rc/Library/Application Support/Sublime Text 3/Installed Packages/TypescriptCompletion.sublime-package", line 50, in on_query_completions
  File "TSCompletion in /Users/rc/Library/Application Support/Sublime Text 3/Installed Packages/TypescriptCompletion.sublime-package", line 258, in TSC_IsTypeScript
AttributeError: 'NoneType' object has no attribute 'ends with'
`

On line 48, is this statement: 
`
current_file = view.file_name()
`
returns None and the call to the TSC_IsTypeScript(current_file) (line 50) tries to see if the filename ends with .ts.   I have an untitled file that I'm working on, so I suppose None is a valid state for the file_name to be in.  As soon as I save it, it no longer has this error, this definitely an edge case.

**Comment by zhengbli** [comment]
It is a known issue that unsaved buffers are not supported right now, because the project system doesn't know how to deal with it currently. The status can be tracked at https://github.com/Microsoft/TypeScript/issues/4526
