### ISSUE TITLE
Auto complete show not only own properties/methods

### ISSUE THREAD

**Issue by SET001** [Microsoft/TypeScript-Sublime-Plugin#607]
For some reason I'm getting a lot of suggestions so I can't find what I need:

![sublimetypescript](https://cloud.githubusercontent.com/assets/30506/25879740/f94ecd68-353b-11e7-9c96-12eab8607001.png)

My tsconfig:
```

{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "watch": false,
    "types": []
  }
}

```

How this can be fixed?

Also if I open console (View -> Show Console) I see following:

```
insert
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "TSCompletion in /home/set/.config/sublime-text-3/Installed Packages/TypescriptCompletion.sublime-package", line 52, in on_query_completions
  File "TSCompletion in /home/set/.config/sublime-text-3/Installed Packages/TypescriptCompletion.sublime-package", line 38, in startThread
  File "TSCompletion in /home/set/.config/sublime-text-3/Installed Packages/TypescriptCompletion.sublime-package", line 70, in stop
AttributeError: 'TsCompletionThread' object has no attribute '_Thread__stop'
```

**Comment by menosprezzi** [comment]
Hey how you fixed it? (if you)

**Comment by siemiatj** [comment]
@SET001 why you closed this one ? I'm getting the same error.

**Comment by SET001** [comment]
@siemiatj  I don't remember how I solved that, but if I closed it this mean that issue has nothing to do with plugin.
