### ISSUE TITLE
ValueError... at json.load(cache_file)

### ISSUE THREAD

**Issue by Ivanca** [Microsoft/TypeScript-Sublime-Plugin#609]
```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Ivan\AppData\Roaming\Sublime Text 3\Packages\Gulp\gulp.py", line 220, in run_process
    process.run(task)
  File "C:\Users\Ivan\AppData\Roaming\Sublime Text 3\Packages\Gulp\cross_platform_process.py", line 41, in run
    ProcessCache.add(self)
  File "C:\Users\Ivan\AppData\Roaming\Sublime Text 3\Packages\Gulp\caches.py", line 40, in add
    cls.storage().update(lambda procs: procs + [process] if process not in procs else procs)
  File "C:\Users\Ivan\AppData\Roaming\Sublime Text 3\Packages\Gulp\caches.py", line 132, in update
    current_data = json.load(cache_file)
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: 
```

**Comment by Ivanca** [comment]
**Solution**
I was getting the error, after some debugging I found out the problem is that the json cache file (cache_file) was corrupt, the one at `%userprofile%\AppData\Roaming\Sublime Text 3\Packages\Gulp\.sublime-gulp.cache` so I deleted its content and put the default .cache content, meaning just `[]` (yeah, only those 2 characters in the file).

If you cant find the corrupted cache file, you may open caches.py and add `print("PATH: " + self.cache_path);` so you can see its path in the console (View > Show Console)

Good luck
