### ISSUE TITLE
Stop spamming ERROR: can not send request; node process not running, on my console

### ISSUE THREAD

**Issue by evandrocoan** [Microsoft/TypeScript-Sublime-Plugin#618]
I have this package installed on my Sublime Text on a machine where I do not have `node` installed. So it is expected it to not work, however this should not keep spamming my console with these messages every time some thing happens:
```
unloading plugin MaxPane.layouts_doc
unloading plugin MaxPane.max_pane
unloading plugin MultiEditUtils.MultiEditUtils
unloading plugin MultiEditUtils.selection_fields
unloading plugin UnitTesting.ut
2017-09-11 11:41:29,232: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:29,241: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:29,251: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:29,261: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:29,267: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:29,282: -1219987712: ERROR: can not send request; node process not running
reloading settings Packages/User/Package Control.sublime-settings
Unable to parse binding {keys: [ctrl+alt+w]}
Unable to parse binding {keys: [ctrl+shift+w]}
Unable to parse binding {keys: [ctrl+alt+w]}
Unable to parse binding {keys: [ctrl+shift+w]}
reloading settings Packages/User/Preferences.sublime-settings
2017-09-11 11:41:31,854: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:31,865: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:31,877: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:31,886: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:31,889: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:31,892: -1219987712: ERROR: can not send request; node process not running
Package Control: The dependency 'python-markdown' is installed, but out of date; upgrading to latest release 2.6.9 from 2.6.6...
Package Control: The dependency 'python-markdown' has successfully been installed or updated
Package Control: Upgraded GitGutter to 1.7.4
Package Control: Upgraded MaxPane to 2017.09.06.17.38.05
ignored packages updated to: ["All Autocomplete", "Anaconda", "ApplySyntax", "BracketHighlighter", "C++ Completions", "C++ Snippets", "C++ Starting Kit", "ColorHelper", "DictionaryAutoComplete", "FileManager", "Find++", "FuzzyFilePath", "Gist", "Git", "GitGutter", "GotoLastEditEnhanced", "Javatar", "Jedi - Python autocompletion", "Local History", "Matlab Completions", "MatlabFilenameAutoComplete", "MultiEditUtils", "MySQL Snippets", "Project Specific Syntax Settings", "Qt Completions for C++", "ScopeAlways", "sublime-text-2-buildview", "SublimeCodeIntel", "SyncedSideBar", "UnitTesting", "Vintage", "WordHighlight"]
2017-09-11 11:41:40,153: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:40,158: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:40,164: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:40,169: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:40,175: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:40,182: -1219987712: ERROR: can not send request; node process not running
reloading plugin MaxPane.layouts_doc
reloading plugin MaxPane.max_pane
Unable to parse binding {keys: [ctrl+alt+w]}
Unable to parse binding {keys: [ctrl+shift+w]}
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
2017-09-11 11:41:41,527: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:41,534: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:41,543: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:41,551: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:41,561: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:41,574: -1219987712: ERROR: can not send request; node process not running
ignored packages updated to: ["All Autocomplete", "Anaconda", "ApplySyntax", "BracketHighlighter", "C++ Completions", "C++ Snippets", "C++ Starting Kit", "ColorHelper", "DictionaryAutoComplete", "FileManager", "Find++", "FuzzyFilePath", "Gist", "Git", "GitGutter", "GotoLastEditEnhanced", "Javatar", "Jedi - Python autocompletion", "Local History", "Matlab Completions", "MatlabFilenameAutoComplete", "MySQL Snippets", "Project Specific Syntax Settings", "Qt Completions for C++", "ScopeAlways", "sublime-text-2-buildview", "SublimeCodeIntel", "SyncedSideBar", "UnitTesting", "Vintage", "WordHighlight"]
2017-09-11 11:41:43,569: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:43,577: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:43,586: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:43,598: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:43,609: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:43,622: -1219987712: ERROR: can not send request; node process not running
Package Control: Upgraded MultiEditUtils to 1.8.3
reloading plugin MultiEditUtils.MultiEditUtils
reloading plugin MultiEditUtils.selection_fields
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
2017-09-11 11:41:45,342: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:45,346: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:45,349: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:45,352: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:45,355: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:45,359: -1219987712: ERROR: can not send request; node process not running
Unable to parse binding {keys: [ctrl+alt+w]}
Unable to parse binding {keys: [ctrl+shift+w]}
reloading settings Packages/User/Preferences.sublime-settings
2017-09-11 11:41:46,568: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:46,572: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:46,577: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:46,586: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:46,590: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:46,596: -1219987712: ERROR: can not send request; node process not running
Package Control: Upgraded UnitTesting to 1.0.6
ignored packages updated to: ["All Autocomplete", "Anaconda", "ApplySyntax", "BracketHighlighter", "C++ Completions", "C++ Snippets", "C++ Starting Kit", "ColorHelper", "DictionaryAutoComplete", "FileManager", "Find++", "FuzzyFilePath", "Gist", "Git", "GitGutter", "GotoLastEditEnhanced", "Javatar", "Jedi - Python autocompletion", "Local History", "Matlab Completions", "MatlabFilenameAutoComplete", "MySQL Snippets", "Project Specific Syntax Settings", "Qt Completions for C++", "ScopeAlways", "sublime-text-2-buildview", "SublimeCodeIntel", "SyncedSideBar", "Vintage", "WordHighlight"]
2017-09-11 11:41:50,266: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:50,271: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:50,279: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:50,285: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:50,290: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:50,296: -1219987712: ERROR: can not send request; node process not running
reloading plugin UnitTesting.ut
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "ut in /home/linux/.config/sublime-text-3/Installed Packages/UnitTesting.sublime-package", line 19, in <module>
ImportError: cannot import name UnitTestingCurrentPackageCommand
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
2017-09-11 11:41:51,308: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:51,316: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:51,324: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:51,326: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:51,328: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:51,331: -1219987712: ERROR: can not send request; node process not running
reloading settings Packages/User/Preferences.sublime-settings
2017-09-11 11:41:52,132: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:52,135: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:52,139: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:52,142: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:52,152: -1219987712: ERROR: can not send request; node process not running
2017-09-11 11:41:52,157: -1219987712: ERROR: can not send request; node process not running
2017-09-11 12:18:20,745: -1219987712: ERROR: can not send request; node process not running
```

Showing this message one time show is more than enough to know what is happening

**Comment by DanielRosenwasser** [comment]
If you didn't want it running, why not set `enable_typescript_language_service` to `false` in your settings?

**Comment by evandrocoan** [comment]
I want it running, if I have `node` installed on my machine. I share my settings across machines and some of them do not have node installed. Therefore, the ideal behavior would just not to start node if there is no node to start.

**Comment by acheronfail** [comment]
Perhaps adding a `debug` option in settings which enables more verbose logging might be a solution?

**Comment by wbond** [comment]
I recently ran into this. I had installed the package to have a TypeScript syntax definition.

I would seem to be that sending this message once, or even once every minute should be sufficient.

An even better enhancement would be to prefix the error message with some useful info like:

```
TypeScript:
```

Leading with a timestamp including fractional seconds and some huge negative int is very odd looking.
