### ISSUE TITLE
Error：NOT work!

### ISSUE THREAD

**Issue by jingyuexing** [Microsoft/TypeScript-Sublime-Plugin#696]
```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "D:\Sublime Text 3157 x64Dev\Data\Packages\TypeScript\typescript\libs\node_client.py", line 146, in monitorPostQueue
    self.server_proc.stdin.flush()
OSError: [Errno 22] Invalid argument
```
****How can i fix this Error**

**Comment by harisb2012** [comment]
Getting the same issue

**Comment by jingyuexing** [comment]
I Installed two plugins，TypeScript and JavaScript Enhancements,but,These two plugins have collision。This plugin covered JavaScript syntax.Even including HTML syntax

**Comment by huljar** [comment]
I'm having the same issue, but I don't have JavaScript Enhancements installed. It doesn't happen when Sublime starts up, but when I hover/click a symbol in the source code for the first time.

Is there any update on this issue?

**Comment by hatched-danny** [comment]
+1
